version: '3.8'
services:
  vacatic-backend:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vacaticadmin123
      POSTGRES_DB: vacaticdev
    networks:
      - vacatic 
networks:
  vacatic: