-- AlterTable
ALTER TABLE "Room" ADD COLUMN     "roomBedroomDouble" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "roomBedroomSingle" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "roomFacility" TEXT[] DEFAULT ARRAY['wifi']::TEXT[],
ADD COLUMN     "roomGuestCount" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "roomKitchenCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "roomRestroomCount" INTEGER NOT NULL DEFAULT 1,
ALTER COLUMN "roomType" SET NOT NULL,
ALTER COLUMN "roomType" DROP DEFAULT,
ALTER COLUMN "roomType" SET DATA TYPE TEXT;
